#!/bin/bash

# Gather system data into variables

# Hostname and username
HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATETIME=$(date "+%Y-%m-%d %H:%M:%S")

# OS name and version from /etc/os-release
source /etc/os-release
OS="$NAME $VERSION"

# Uptime (pretty format)
UPTIME=$(uptime -p)

# CPU info (manufacturer and model)
CPU=$(lscpu | grep "Model name:" | sed 's/Model name:[ \t]*//')

# RAM total size (in MB)
RAM=$(free -m | awk '/^Mem:/ {print $2 " MB"}')

# Physical Disk info: name, model and size (exclude loop, floppy, cdrom)
DISKS=$(lsblk -d -o NAME,MODEL,SIZE | grep -E '^(sd|nvme|vd|xvd)' | awk '{print $1": "$2" "$3}')

# Video card (make and model)
VIDEO=$(lshw -C display 2>/dev/null | grep "product:" | head -1 | sed 's/.*product: //')

# IP address of the interface connected to default gateway
DEF_IFACE=$(ip route | grep default | awk '{print $5}' | head -1)
HOST_IP=$(ip -4 addr show "$DEF_IFACE" | grep -oP '(?<=inet\s)\d+(\.\d+){3}')

# Gateway IP address
GATEWAY_IP=$(ip route | grep default | awk '{print $3}')

# DNS server IP - try to get upstream DNS rather than local stub
DNS_SERVER=$(resolvectl status | grep 'DNS Servers' | head -1 | awk '{print $3}')
if [ -z "$DNS_SERVER" ]; then
    DNS_SERVER=$(grep '^nameserver' /etc/resolv.conf | head -1 | awk '{print $2}')
fi

# Users logged in (comma separated)
USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd "," -)

# Disk free space for local filesystems (mount point and free space)
DISKSPACE=$(df -h --output=target,avail -x tmpfs -x devtmpfs | awk 'NR>1 {print $1 ": " $2 " free"}')

# Process count
PROCESS_COUNT=$(ps aux --no-heading | wc -l)

# Load averages (1, 5, 15 minutes)
LOAD_AVG=$(uptime | grep -oP 'load average[s]?: \K.*')

# Listening network ports (TCP and UDP, unique, sorted, comma separated)
PORTS=$(ss -tuln | awk 'NR>1 && $5 ~ /:/ {split($5,a,":"); print a[length(a)]}' | sort -n | uniq | paste -sd ", " -)

# UFW status
UFW_STATUS=$(sudo ufw status | head -1)

# Output report using a here-doc with variables
cat <<EOF

System Report for $HOSTNAME generated by $USERNAME, on $DATETIME

System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s):
$DISKS
Video: $VIDEO
Host Address: $HOST_IP
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $USERS
Disk Space:
$DISKSPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVG
Listening Network Ports: $PORTS
UFW Status: $UFW_STATUS

EOF

